version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/test:/db/test
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      PG_DATA: /db/test
